services:
  frontend:
    build: ./mobile-shop
    ports:
      - "5173:5173"
    volumes:
      - ./mobile-shop:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

  backend:
    build: ./Server
    ports:
      - "4242:4242"
    volumes:
      - ./Server:/app
      - /app/node_modules
    environment:
      - PORT=4242
      - SECRET_KEY=${SECRET_KEY}
      - FRONTEND_URL=http://localhost:5173
    command: npm run dev